version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - BTCD_CONNECT
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    lnd:
        image: lnd
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
          - shared:/rpc

    lnd_hub:
      extends: lnd
      container_name: lnd_hub
      hostname: lnd_hub
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    lnd_alice:
      extends: lnd
      container_name: lnd_alice
      hostname: lnd_alice
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    lnd_bob:
      extends: lnd
      container_name: lnd_bob
      hostname: lnd_bob
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    bitcuddle:
      image: bitcuddle
      volumes:
        - shared:/rpc
        - $PWD:/mnt
      links:
        - "lnd_alice:lnd_alice"
        - "lnd_bob:lnd_bob"
      environment:
        - LND_PEER_HOST
        - LND_PEER_PUBKEY

volumes:
  # shared volume is need to store the btcd rpc certificates and us it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistance
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistance
  # during ltcd container recreation.
  litecoin:
    driver: local
