version: '2'
services:
    btc:
      image: btcd
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcwallet:
        image: btcwallet
        build: btcwallet
        container_name: btcwallet
        volumes:
          - shared:/rpc
          - btcwallet:/data
        links:
          - "btcd:btcd"
        environment:
          - RPC_CONNECT=btcd
        entrypoint: ["./start-btcwallet.sh"]

    lnd:
        image: lnd
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
          - shared:/rpc

    lnd_hub:
      extends: lnd
      container_name: lnd_hub
      hostname: lnd_hub
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    lnd_alice:
      extends: lnd
      container_name: lnd_alice
      hostname: lnd_alice
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    lnd_bob:
      extends: lnd
      container_name: lnd_bob
      hostname: lnd_bob
      links:
        - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

    bitcuddle:
      image: bitcuddle
      build: .
      environment:
        - MINING_PRIVATE_KEY
      volumes:
        - shared:/rpc
        - $PWD:/mnt
      links:
        - "lnd_alice:lnd_alice"
        - "lnd_bob:lnd_bob"
        - "btcwallet:btcwallet"

volumes:
  # a place to store keys, certificates and other data needed for inter-service communication
  shared:
    driver: local

  # a place to store the blockchain data
  bitcoin:
    driver: local

  # a place to store the btcwallet wallet
  btcwallet:
    driver: local
  
