version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - BTCD_CONNECT
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    lnd_btc:
        image: lnd
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
          - shared:/rpc
        entrypoint: ["./start-lnd.sh"]
        container_name: lnd_btc
        hostname: lndrpc
        links:
          - "btcd:blockchain"

    bitcuddle:
      image: bitcuddle
      volumes:
        - shared:/rpc
      links:
        - "lnd_btc:lndrpc"
      environment:
        - LND_PEER_HOST
        - LND_PEER_PUBKEY

volumes:
  # shared volume is need to store the btcd rpc certificates and us it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistance
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistance
  # during ltcd container recreation.
  litecoin:
    driver: local
