#!/bin/sh

for name in alice bob; do
  json=$(docker-compose exec lnd_$name lncli --no-macaroons newaddress p2wkh)
  address=$(echo "$json" | jq -r .address)
  echo "address: $address"
  ssh compute ./faucet "$address" 1000000
done
